spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://39.106.215.155/weixin?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
